import { demand } from '../execution';
import { rational } from '../algebra/rational';
import { ALGEBRAIC_RING, realRoots, type RealRootOf } from '../algebraic/root-of';
import { normPolynomial } from '../decision/algebraic-coefficients';
import { addValues, multiplyValues, normalizeValue, type ExactValue } from '../representation/evaluate';
import type { ExpressionStore } from '../representation/expression';
import {
  coefficientsBelow, constant, degree, degrees, derivativeIn, isZero, permute, resultant, substitute, trueLevel, type RPoly,
} from './recursive';
import { signAtPoint } from './sign';

/**
 * The fibre of a level-k polynomial over a sample point α ∈ ℝ^(k−1) of real algebraic coordinates: the distinct real
 * roots of f(α, xₖ), as exact values with their minimal polynomials over ℚ.
 *
 * Rational coordinates are substituted. For algebraic ones the norm N(xₖ) = res_{x₁}(m₁, … res_{x_{k−1}}(m_{k−1}, f)),
 * mⱼ the minimal polynomial of αⱼ, is the product of f over the tuples of conjugates and vanishes at every root of
 * f(α, xₖ); when it vanishes identically (f vanishes identically at a conjugate tuple), the norm over the field
 * generated by f(α, xₖ)'s own coefficient values is used instead, which never vanishes identically
 * (decision/algebraic-coefficients.ts). Each real root of the norm is a candidate, kept exactly when f vanishes at
 * (α, candidate) (sign.ts).
 *
 * When f(α, xₖ) vanishes identically (f is nullified over the cell), the fibre is that of the Lazard evaluation:
 * for j = 1 … k − 1 in turn, the least-order partial derivative in xⱼ that does not vanish identically at
 * x₁ = α₁ … xⱼ = αⱼ (McCallum, Parusiński and Paunescu, "Validity proof of Lazard's method for CAD", J. Symbolic
 * Comput. 92, 2019). Over a cell where Lazard's projection is valuation-invariant the Lazard valuation is constant,
 * so the same derivative is the Lazard evaluation at every point of the cell.
 */
/** Whether a level-m polynomial vanishes at the first m coordinates of α. */
const vanishesAt = (store: ExpressionStore, a: RPoly, m: number, alpha: readonly ExactValue[]) => signAtPoint(store.ctx, a, m, alpha) === 0;

/** Whether f(α, xₖ) vanishes identically (every coefficient in xₖ vanishes at α). */
export function nullified(store: ExpressionStore, f: RPoly, k: number, alpha: readonly ExactValue[]): boolean {
  return coefficientsBelow(f, k, k - 1).every(c => isZero(c) || vanishesAt(store, c, k - 1, alpha));
}

/**
 * The Lazard evaluation of f over α as a polynomial over ℤ in x₁ … xₖ (a mixed partial derivative of f; f itself
 * when f(α, xₖ) does not vanish identically), with the derivative orders.
 */
export function lazardPolynomial(store: ExpressionStore, f: RPoly, k: number, alpha: readonly ExactValue[]): { readonly poly: RPoly; readonly orders: readonly number[] } {
  const ctx = store.ctx, orders: number[] = [];
  let g = f;
  for (let j = 1; j < k; j++) {
    let m = 0;
    // Identically zero at x₁ = α₁ … xⱼ = αⱼ: every coefficient in the monomials of x_{j+1} … xₖ vanishes there.
    while (coefficientsBelow(g, k, j).every(c => isZero(c) || vanishesAt(store, c, j, alpha))) {
      ctx.tick();
      g = derivativeIn(ctx, g, k, j);
      m++;
      demand(!isZero(g), 'verification-failed', 'a nonzero polynomial vanished identically under derivatives');
    }
    orders.push(m);
  }
  return { poly: g, orders };
}

/** The univariate integer coefficients of a level-k polynomial that depends on xₖ only (ascending). */
function univariate(a: RPoly, k: number): bigint[] {
  return (a as readonly RPoly[]).map(c => {
    const t = trueLevel(c, k - 1);
    demand(t.level === 0, 'verification-failed', 'a norm still depends on a coordinate');
    return t.poly as bigint;
  });
}

/** res_{xⱼ}(mⱼ(xⱼ), a) for a level-k polynomial a; the result is level k with xⱼ absent. */
function eliminate(store: ExpressionStore, a: RPoly, k: number, j: number, m: readonly bigint[]): RPoly {
  const ctx = store.ctx;
  // xⱼ becomes the main variable, the others keep their order below it.
  const toMain = Array.from({ length: k }, (_, i) => (i + 1 === j ? k : i + 1 < j ? i + 1 : i));
  const moved = permute(ctx, a, k, toMain, k);
  const mPoly = Object.freeze(m.map(c => constant(c, k - 1)));
  const r = resultant(ctx, mPoly, moved, k);
  // Back to level k with a hole at xⱼ.
  const back = Array.from({ length: k - 1 }, (_, i) => (i + 1 < j ? i + 1 : i + 2));
  return permute(ctx, r, k - 1, back, k);
}

/** f's coefficient values in xₖ at α, exactly (algebraic arithmetic), trimmed so the last is nonzero. */
function coefficientValues(store: ExpressionStore, f: RPoly, k: number, alpha: readonly ExactValue[]): ExactValue[] {
  const ctx = store.ctx;
  const valueOf = (a: RPoly, m: number): ExactValue => {
    if (m === 0) return { kind: 'rational', value: rational(ctx, a as bigint) };
    const c = a as readonly RPoly[];
    let acc: ExactValue = { kind: 'rational', value: rational(ctx, 0n) };
    for (let i = c.length - 1; i >= 0; i--) acc = addValues(ctx, multiplyValues(ctx, acc, alpha[m - 1]), valueOf(c[i], m - 1));
    return acc;
  };
  const out = (f as readonly RPoly[]).map(c => valueOf(c, k - 1));
  while (out.length && out[out.length - 1].kind === 'rational' && (out[out.length - 1] as { value: { numerator: bigint } }).value.numerator === 0n) out.pop();
  return out;
}

const rootValue = (r: RealRootOf): ExactValue => normalizeValue(r);

/**
 * The distinct real roots of f(α, xₖ), ascending, or 'nullified' when it vanishes identically. α holds at least
 * k − 1 real coordinates.
 */
export function fiberRoots(store: ExpressionStore, f: RPoly, k: number, alpha: readonly ExactValue[]): ExactValue[] | 'nullified' {
  const ctx = store.ctx;
  let a = f;
  const degs = degrees(a, k);
  for (let j = 1; j < k; j++) if (degs[j - 1] > 0 && alpha[j - 1].kind === 'rational') a = substitute(ctx, a, k, j, (alpha[j - 1] as Extract<ExactValue, { kind: 'rational' }>).value);
  const algebraic = degrees(a, k).slice(0, k - 1).flatMap((d, i) => (d > 0 ? [i + 1] : []));
  if (algebraic.length === 0) {
    const c = univariate(a, k);
    if (c.every(v => v === 0n)) return 'nullified';
    if (c.length <= 1) return [];
    return realRoots(ctx, ALGEBRAIC_RING.make(ctx, c)).map(r => rootValue(r.root));
  }
  if (nullified(store, a, k, alpha)) return 'nullified';
  if (degree(a) <= 0) return [];
  let norm = a;
  for (const j of [...algebraic].reverse()) {
    ctx.tick();
    norm = eliminate(store, norm, k, j, ((alpha[j - 1] as Extract<ExactValue, { kind: 'algebraic' }>).root as RealRootOf).poly.coefficients);
  }
  let candidates: RealRootOf[];
  const n = univariate(norm, k);
  if (n.some(v => v !== 0n)) {
    candidates = n.length <= 1 ? [] : realRoots(ctx, ALGEBRAIC_RING.make(ctx, n)).map(r => r.root);
  } else {
    const values = coefficientValues(store, a, k, alpha);
    candidates = values.length <= 1 ? [] : realRoots(ctx, normPolynomial(store, values)).map(r => r.root);
  }
  const out: ExactValue[] = [];
  for (const r of candidates) {
    ctx.tick();
    const v = rootValue(r);
    if (signAtPoint(ctx, a, k, [...alpha.slice(0, k - 1), v]) === 0) out.push(v);
  }
  return out;
}
