export {
  appendHistoryEntry,
  bootApp,
  clearCalculatorMemorySnapshot,
  clearHistoryEntries,
  deleteHistoryEntry,
  isDesktopRuntime,
  loadCalculatorMemorySnapshot,
  loadHistoryEntries,
  loadLauncherCategories,
  persistCalculatorMemorySnapshot,
  persistMode,
  persistSettings,
  persistVariableMemory,
} from './tauri';
