export type {
  ExactPolynomial,
  ExactPolynomialDivisionResult,
  ExactScalar,
} from './polynomial-core/index';
export {
  addExactPolynomials,
  addExactScalars,
  buildExactPolynomialFromCoefficients,
  buildExactScalarNode,
  divideExactPolynomials,
  divideExactScalars,
  exactPolynomialCoefficientArray,
  exactPolynomialConstantTerm,
  exactPolynomialContent,
  exactPolynomialDegree,
  exactPolynomialGcd,
  exactPolynomialIsZero,
  exactPolynomialLeadingCoefficient,
  exactPolynomialToLatex,
  exactPolynomialToNode,
  exactScalarEquals,
  exactScalarIsZero,
  exactScalarToNumber,
  getExactPolynomialCoefficient,
  makeMonicExactPolynomial,
  multiplyExactPolynomials,
  multiplyExactScalars,
  negateExactScalar,
  normalizeExactPolynomial,
  normalizeExactScalar,
  parseExactPolynomial,
  primitiveExactPolynomial,
  quadraticDiscriminant,
  readExactScalarNode,
  scaleExactPolynomial,
  subtractExactScalars,
} from './polynomial-core/index';
