export type FricasContextArea =
  | 'architecture'
  | 'type-system'
  | 'expression-model'
  | 'integration'
  | 'limits'
  | 'polynomial-algebra'
  | 'groebner-elimination'
  | 'regular-chains'
  | 'linear-algebra'
  | 'solving'
  | 'simplification'
  | 'series-special-functions';

export type FricasReferenceCase = {
  id: string;
  area: FricasContextArea;
  sourcePath: string;
  problemFamily: string;
  representativeInput: string;
  intendedCalcwizUse: string;
  boundaryNotes: string;
};

export const FRICAS_REFERENCE_CORPUS: FricasReferenceCase[] = [
  {
    id: 'arch-runtime-domain-vectors',
    area: 'architecture',
    sourcePath: 'doc/runtime.txt',
    problemFamily: 'runtime representation of mathematical domains and categories',
    representativeInput: 'domain constructor cache and domain vector model',
    intendedCalcwizUse: 'Inspire explicit capability descriptors for bounded algebra cores.',
    boundaryNotes: 'Do not copy FriCAS runtime type machinery or make Calcwiz type constructors executable objects.',
  },
  {
    id: 'arch-bootstrap-database-stages',
    area: 'architecture',
    sourcePath: 'doc/algebra_build.txt',
    problemFamily: 'large algebra library bootstrap and dependency management',
    representativeInput: 'multi-stage constructor/database build',
    intendedCalcwizUse: 'Study costs of rich algebra APIs before adding new core registries.',
    boundaryNotes: 'Calcwiz should avoid FriCAS-scale bootstrap complexity.',
  },
  {
    id: 'interp-type-resolution-towers',
    area: 'type-system',
    sourcePath: 'src/interp/i-resolv.boot',
    problemFamily: 'type resolution across algebraic towers and coercions',
    representativeInput: 'Polynomial(Integer) with Fraction(Integer)',
    intendedCalcwizUse: 'Motivate small typed carriers and explicit coercion refusal reasons.',
    boundaryNotes: 'No general FriCAS-style mode tower is planned for stable Calcwiz.',
  },
  {
    id: 'interp-coercion-contracts',
    area: 'type-system',
    sourcePath: 'src/interp/i-coerce.boot',
    problemFamily: 'interactive coercion, retraction, and convertibility checks',
    representativeInput: 'constant polynomial retraction into coefficient domain',
    intendedCalcwizUse: 'Guide bounded conversion adapters between expression, polynomial, rational, and matrix carriers.',
    boundaryNotes: 'Keep conversions explicit and local; do not add global magical coercion.',
  },
  {
    id: 'interp-database-autoload',
    area: 'architecture',
    sourcePath: 'src/interp/daase.lisp',
    problemFamily: 'operation/category database lookup and lazy constructor data',
    representativeInput: 'constructor metadata loaded from database on demand',
    intendedCalcwizUse: 'Inform future plugin/module registries without making current app dynamic.',
    boundaryNotes: 'No runtime loading of external algebra packages in v1.',
  },
  {
    id: 'expr-kernel-function-space',
    area: 'expression-model',
    sourcePath: 'src/algebra/expr.spad',
    problemFamily: 'symbolic expression as function-space over kernels',
    representativeInput: 'Expression(Integer) with elementary and algebraic kernels',
    intendedCalcwizUse: 'Compare with Calcwiz AST plus carrier-recognition approach.',
    boundaryNotes: 'Do not replace Calcwiz AST with FriCAS kernel representation.',
  },
  {
    id: 'expr-denominator-simplification-flag',
    area: 'simplification',
    sourcePath: 'src/algebra/expr.spad',
    problemFamily: 'configurable algebraic denominator simplification',
    representativeInput: 'sqrt denominator normalization',
    intendedCalcwizUse: 'Inspire explicit simplification policy switches if Calcwiz later exposes modes.',
    boundaryNotes: 'No hidden global simplification flags in user-facing evaluation.',
  },
  {
    id: 'elementary-function-operator-table',
    area: 'expression-model',
    sourcePath: 'src/algebra/elemntry.spad',
    problemFamily: 'elementary function operator family and local real behavior',
    representativeInput: 'sin, cos, log, exp, inverse trig, inverse hyperbolic',
    intendedCalcwizUse: 'Strengthen a bounded known-function registry for calculus/domain handling.',
    boundaryNotes: 'Registry should stay data-driven and bounded, not a full FriCAS function space.',
  },
  {
    id: 'integration-top-level-risch-normalize',
    area: 'integration',
    sourcePath: 'src/algebra/integrat.spad',
    problemFamily: 'top-level integration normalization before elementary integration',
    representativeInput: 'rischNormalize followed by lfintegrate',
    intendedCalcwizUse: 'Guide future strategy-normalization layers after current bounded integration rules.',
    boundaryNotes: 'No full Risch engine in stable Calcwiz from this milestone.',
  },
  {
    id: 'integration-unknown-derivative-denominator',
    area: 'integration',
    sourcePath: 'src/algebra/intef.spad',
    problemFamily: 'fallback recognizing numerator over derivative of denominator',
    representativeInput: 'c * denominatorDerivative / denominator -> c log(denominator)',
    intendedCalcwizUse: 'Compare with existing derivative-ratio integration strategy.',
    boundaryNotes: 'Only adopt via verified Calcwiz-native derivative-ratio rules.',
  },
  {
    id: 'integration-complex-trig-rewrite',
    area: 'integration',
    sourcePath: 'src/algebra/integrat.spad',
    problemFamily: 'trigonometric conversion through exp/log forms for integration',
    representativeInput: 'tan/cot tower conversion before integration',
    intendedCalcwizUse: 'Potential Playground-only integration strategy experiment.',
    boundaryNotes: 'Avoid branch-heavy rewrite in stable code without domain proof.',
  },
  {
    id: 'integration-parametric',
    area: 'integration',
    sourcePath: 'src/algebra/intpar.spad',
    problemFamily: 'parametric integration over symbolic parameters',
    representativeInput: 'integrals with parameters in coefficients',
    intendedCalcwizUse: 'Long-term context for parameter-aware exact-first integration.',
    boundaryNotes: 'Blocked until Calcwiz has stronger assumptions/domain support.',
  },
  {
    id: 'integration-definite-elementary',
    area: 'integration',
    sourcePath: 'src/algebra/defintef.spad',
    problemFamily: 'definite integration of elementary functions with pole checks',
    representativeInput: 'integrate(f, x = a..b, noPole)',
    intendedCalcwizUse: 'Inform future CALC-INT2 safety and proof vocabulary.',
    boundaryNotes: 'Current Calcwiz interval safety remains bounded and domain-core based.',
  },
  {
    id: 'integration-test-atan-square',
    area: 'integration',
    sourcePath: 'src/input/bugs2007.input',
    problemFamily: 'inverse-trig integration regression family',
    representativeInput: 'integrate(2*atan(x)/(1+x^2), x)',
    intendedCalcwizUse: 'Future challenge case for integration-by-composition plus inverse trig.',
    boundaryNotes: 'Challenge only; not a current Calcwiz promise.',
  },
  {
    id: 'integration-test-power-parametric',
    area: 'integration',
    sourcePath: 'src/input/bugs2007.input',
    problemFamily: 'parameterized power integrands verified by differentiation',
    representativeInput: 'D(integrate((z^a+1)^b, z), z)',
    intendedCalcwizUse: 'Long-term evidence for derivative-backed antiderivative verification.',
    boundaryNotes: 'Parameter-dependent integration remains out of stable scope.',
  },
  {
    id: 'limit-power-series-package',
    area: 'limits',
    sourcePath: 'src/algebra/limitps.spad',
    problemFamily: 'finite/infinite limits through Laurent, Puiseux, and exponential expansions',
    representativeInput: 'PowerSeriesLimitPackage realLimit and locallimit',
    intendedCalcwizUse: 'Context for future bounded local-equivalent and asymptotic slices.',
    boundaryNotes: 'Do not introduce a general series/asymptotic engine without a separate milestone.',
  },
  {
    id: 'limit-mrv-gruntz',
    area: 'limits',
    sourcePath: 'src/algebra/mrv_limit.spad',
    problemFamily: 'MRV set, rewrite, and generalized series for limits',
    representativeInput: 'mrv_limit(log(x)/exp(x), x = infinity)',
    intendedCalcwizUse: 'Long-term model for asymptotic ordering and dominance research.',
    boundaryNotes: 'Stable Calcwiz remains bounded rational/local-equivalent first.',
  },
  {
    id: 'limit-special-functions',
    area: 'limits',
    sourcePath: 'src/input/limit.input',
    problemFamily: 'special-function asymptotic limit families',
    representativeInput: 'Gamma, digamma, dilog, erf, erfi, li near infinity',
    intendedCalcwizUse: 'Future challenge corpus for special-function boundary decisions.',
    boundaryNotes: 'Not near-term; Calcwiz does not currently own broad special functions.',
  },
  {
    id: 'limit-composition-ratio',
    area: 'limits',
    sourcePath: 'src/input/limit.input',
    problemFamily: 'composed small-angle trigonometric ratios',
    representativeInput: 'limit(sin(a*x)/tan(b*x), x=0)',
    intendedCalcwizUse: 'Potential extension of existing bounded local-equivalent limit rules.',
    boundaryNotes: 'Requires parameter assumptions before stable adoption.',
  },
  {
    id: 'limit-directional-identity',
    area: 'limits',
    sourcePath: 'src/input/limit.input',
    problemFamily: 'left/right finite limit API behavior',
    representativeInput: 'limit(1/z, z = z, "right")',
    intendedCalcwizUse: 'Compare against Calcwiz typed directional target surface.',
    boundaryNotes: 'Only UI/API lessons; do not inherit FriCAS syntax.',
  },
  {
    id: 'poly-category-general',
    area: 'polynomial-algebra',
    sourcePath: 'src/algebra/polycat.spad',
    problemFamily: 'general multivariate polynomial category over coefficient rings',
    representativeInput: 'PolynomialCategory(Dom, Expon, VarSet)',
    intendedCalcwizUse: 'Guide future typed polynomial-core capability facts.',
    boundaryNotes: 'Avoid recreating a full category hierarchy prematurely.',
  },
  {
    id: 'poly-factorization-category',
    area: 'polynomial-algebra',
    sourcePath: 'src/algebra/catdef.spad',
    problemFamily: 'explicit factorization capability as category contract',
    representativeInput: 'PolynomialFactorizationExplicit',
    intendedCalcwizUse: 'Model capabilities like factor, gcd, square-free as explicit core facts.',
    boundaryNotes: 'Keep facts narrow and test-backed.',
  },
  {
    id: 'poly-gcd-modular',
    area: 'polynomial-algebra',
    sourcePath: 'src/algebra/modgcd.spad',
    problemFamily: 'modular polynomial gcd and factor-related infrastructure',
    representativeInput: 'modular gcd family',
    intendedCalcwizUse: 'Long-term context for stronger polynomial-core exactness.',
    boundaryNotes: 'No adoption before a dedicated polynomial-core roadmap.',
  },
  {
    id: 'groebner-basic-package',
    area: 'groebner-elimination',
    sourcePath: 'src/algebra/gb.spad',
    problemFamily: 'Grobner basis and normal form for polynomial ideals',
    representativeInput: 'groebner([p1, p2, ...]) and normalForm(poly, gb)',
    intendedCalcwizUse: 'Define a future bounded elimination feasibility lane.',
    boundaryNotes: 'Not a general solver shortcut; requires exact polynomial substrate and UI honesty.',
  },
  {
    id: 'groebner-factorization',
    area: 'groebner-elimination',
    sourcePath: 'src/algebra/groebf.spad',
    problemFamily: 'factorization during Grobner computation for decomposed solution sets',
    representativeInput: 'groebnerFactorize(polys, nonZeroRestrictions)',
    intendedCalcwizUse: 'Context for decomposition-aware equation solving.',
    boundaryNotes: 'Must remain Playground until branch/domain representation matures.',
  },
  {
    id: 'groebner-input-example',
    area: 'groebner-elimination',
    sourcePath: 'src/input/test.input',
    problemFamily: 'small polynomial ideal membership/elimination example',
    representativeInput: 'groebner [x^2 - y, y^3+1]',
    intendedCalcwizUse: 'Tiny future smoke candidate for any bounded Grobner prototype.',
    boundaryNotes: 'Challenge only; not wired into product tests.',
  },
  {
    id: 'regular-set-category',
    area: 'regular-chains',
    sourcePath: 'src/algebra/regset.spad',
    problemFamily: 'regular triangular sets and ideal/variety decomposition',
    representativeInput: 'zeroSetSplit and intersect over triangular sets',
    intendedCalcwizUse: 'Context for branch/decomposition design beyond current branch-core.',
    boundaryNotes: 'Too heavy for stable adoption without a long feasibility lane.',
  },
  {
    id: 'regular-set-lazard-solver',
    area: 'regular-chains',
    sourcePath: 'src/algebra/nsregset.spad',
    problemFamily: 'Lazard triangular decomposition of polynomial systems',
    representativeInput: 'LazardSetSolvingPackage zeroSetSplit',
    intendedCalcwizUse: 'Long-term source for exact system-solving architecture vocabulary.',
    boundaryNotes: 'Not near-term; high risk of identity drift if copied.',
  },
  {
    id: 'matrix-category-layering',
    area: 'linear-algebra',
    sourcePath: 'src/algebra/matcat.spad',
    problemFamily: 'matrix categories with algorithms split into packages',
    representativeInput: 'MatrixCategory plus MatrixLinearAlgebraFunctions',
    intendedCalcwizUse: 'Inform future exact linear algebra API and ownership boundaries.',
    boundaryNotes: 'Translate into small typed matrix-core, not a category hierarchy.',
  },
  {
    id: 'matrix-domain-capability-gates',
    area: 'linear-algebra',
    sourcePath: 'src/algebra/matrix.spad',
    problemFamily: 'linear algebra operations gated by coefficient-domain capabilities',
    representativeInput: 'rowEchelon for EuclideanDomain, inverse for Field',
    intendedCalcwizUse: 'Strong candidate lesson for Calcwiz exact linear algebra readiness.',
    boundaryNotes: 'Adopt conceptually as capability gates only.',
  },
  {
    id: 'solve-basic-tutorial',
    area: 'solving',
    sourcePath: 'src/input/tutchap2.input',
    problemFamily: 'linear, quadratic, radical, and numeric solve examples',
    representativeInput: 'solve(3*x=x+2), solve(x^2-2), radicalSolve(a*x^2+b*x+c,x)',
    intendedCalcwizUse: 'Compare current equation golden corpus and future challenge coverage.',
    boundaryNotes: 'Do not use as parity target.',
  },
  {
    id: 'solve-rational-system-exclusion',
    area: 'solving',
    sourcePath: 'src/input/tutchap2.input',
    problemFamily: 'polynomial systems with rational-expression exclusions',
    representativeInput: 'solve([x^2-y^2, (x^2-1)/(x+y)])',
    intendedCalcwizUse: 'Future domain-guard and candidate-rejection challenge.',
    boundaryNotes: 'Requires stronger domain/range proof before stable expansion.',
  },
  {
    id: 'solve-radical-regression',
    area: 'solving',
    sourcePath: 'src/input/bugs2019.input',
    problemFamily: 'radical solve simplification with symbolic parameters',
    representativeInput: 'radicalSolve(x^2+2*a*x+2*b,x)',
    intendedCalcwizUse: 'Long-term radical-core parameter challenge.',
    boundaryNotes: 'Parameter-domain assumptions make this non-immediate.',
  },
  {
    id: 'solve-trig-system-boundary',
    area: 'solving',
    sourcePath: 'src/input/bugs2012.input',
    problemFamily: 'trig system solving with known exact values',
    representativeInput: 'solve([sin(x)=y,y=0],[x,y])',
    intendedCalcwizUse: 'Challenge current periodic/principal-range solve boundaries.',
    boundaryNotes: 'Needs branch-family honesty; not a broad trig solver promise.',
  },
  {
    id: 'simplify-exp-powers',
    area: 'simplification',
    sourcePath: 'src/input/bugs2024.input',
    problemFamily: 'exponential and power simplification identities',
    representativeInput: 'simplifyExp(a*a^b)',
    intendedCalcwizUse: 'Potential future simplification policy corpus.',
    boundaryNotes: 'Branch/domain assumptions must be explicit for power rewrites.',
  },
  {
    id: 'simplify-square-root-radical',
    area: 'simplification',
    sourcePath: 'src/input/bugs2019.input',
    problemFamily: 'square-root expression simplification inside radical solving',
    representativeInput: 'sqrt(a^2-2*b) with affine parameter shift',
    intendedCalcwizUse: 'Guide exact readback tests for radical-core refinements.',
    boundaryNotes: 'Do not simplify across domains without assumptions.',
  },
  {
    id: 'series-generalized-power-series',
    area: 'series-special-functions',
    sourcePath: 'src/algebra/gseries.spad',
    problemFamily: 'generalized series as algebraic objects',
    representativeInput: 'generalized series operations',
    intendedCalcwizUse: 'Context for future CALC-SER1 architecture.',
    boundaryNotes: 'Stable Calcwiz series should start bounded and display-oriented.',
  },
  {
    id: 'series-taylor-doc',
    area: 'series-special-functions',
    sourcePath: 'doc/sttaylor.txt',
    problemFamily: 'Taylor simplification and mapping examples',
    representativeInput: 'Taylor-series simplification notes',
    intendedCalcwizUse: 'Reference for future series readback and simplification choices.',
    boundaryNotes: 'Documentation context only.',
  },
  {
    id: 'special-functions-limit-corpus',
    area: 'series-special-functions',
    sourcePath: 'src/input/limit.input',
    problemFamily: 'special-function limits around infinity',
    representativeInput: 'Ei(1/x), dilog(1/x), Gamma asymptotics',
    intendedCalcwizUse: 'Long-term challenge corpus for special-function policy.',
    boundaryNotes: 'Outside current Calcwiz capability and not a near-term target.',
  },
  {
    id: 'ode-integration-interface',
    area: 'integration',
    sourcePath: 'src/algebra/oderf.spad',
    problemFamily: 'ODE packages calling integration as a dependency',
    representativeInput: 'particularSolution with integration callback',
    intendedCalcwizUse: 'Reinforce dependency-readiness gates between ODE and integration work.',
    boundaryNotes: 'Do not expand ODE before calculus/integration prerequisites are explicit.',
  },
  {
    id: 'linalg-input-systems',
    area: 'linear-algebra',
    sourcePath: 'src/input/linalg.input',
    problemFamily: 'linear algebra tutorial and regression examples',
    representativeInput: 'matrix rank, inverse, row operations, solve systems',
    intendedCalcwizUse: 'Seed future exact-linear-algebra challenge families.',
    boundaryNotes: 'Requires a separate linear algebra milestone.',
  },
  {
    id: 'numsolve-boundary',
    area: 'solving',
    sourcePath: 'src/algebra/numsolve.spad',
    problemFamily: 'numeric solving as separate capability from exact solving',
    representativeInput: 'numeric root and system solve routines',
    intendedCalcwizUse: 'Compare with Calcwiz exact-first plus numeric-fallback result-origin policy.',
    boundaryNotes: 'Do not blur exact and numeric result surfaces.',
  },
  {
    id: 'pattern-match-assertions',
    area: 'expression-model',
    sourcePath: 'src/algebra/expr.spad',
    problemFamily: 'predicate/assertion attachment for pattern matching',
    representativeInput: 'FunctionSpaceAttachPredicates and PatternMatchAssertions',
    intendedCalcwizUse: 'Potential context for bounded rule preconditions and explainable rewrites.',
    boundaryNotes: 'Keep rule predicates visible and testable.',
  },
  {
    id: 'interpreter-pattern-rules',
    area: 'simplification',
    sourcePath: 'src/interp/rulesets.boot',
    problemFamily: 'interpreter-side rule set machinery',
    representativeInput: 'rule sets and rewrite application',
    intendedCalcwizUse: 'Compare with future Calcwiz rewrite-policy design.',
    boundaryNotes: 'Avoid broad global rewrite systems in stable code.',
  },
];
