export {
  SURFACE_SUPPORTED_WORKSPACE_KINDS,
  buildSurfaceCapabilityManifest,
  getSurfaceWorkspaceCapability,
  isSurfaceWorkspaceKind,
  listSurfaceWorkspaceCapabilities,
  type SurfaceCapabilityFlags,
  type SurfaceCapabilityManifestDto,
  type SurfaceWorkspaceCapabilityDto,
} from './capabilities';

export {
  SURFACE_SUPPORTED_PROTOCOL_VERSIONS,
  SURFACE_SUPPORTED_QUERY_KINDS,
  isSurfaceProtocolVersion,
  isSurfaceQueryKind,
  surfaceError,
  validateSurfaceProtocolVersion,
  validateSurfaceQueryKind,
  validateSurfaceRequest,
  validateSurfaceWorkspaceKind,
  type SurfaceErrorCode,
  type SurfaceQueryKind,
  type SurfaceValidatedRequest,
} from './errors';

export {
  SURFACE_PROTOCOL_VERSION,
  displayOutcomeToSurfaceResultSummary,
  emptySurfaceResultSummary,
  surfaceFailure,
  surfaceOk,
  type SurfaceCountDto,
  type SurfaceCountKind,
  type SurfaceFactDto,
  type SurfaceFactKind,
  type SurfaceFailureDto,
  type SurfaceProtocolVersion,
  type SurfaceResultDto,
  type SurfaceResultKind,
  type SurfaceResultStatus,
  type SurfaceResultSummaryDto,
  type SurfaceWarningDto,
  type SurfaceWorkspaceKind,
} from './dto';
